---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation to create security gropu
Parameters:
  MySecurityGroup:
    Description: 'Security group name'
    Type: String
Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: "Retain"
    Properties:
      GroupName: !Ref MySecurityGroup
      GroupDescription: Enable HTTP and HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref MySecurityGroup
